syntax enable
set nocompatible
set tabstop=4
set softtabstop=4
set showcmd
set cursorline
set wildmenu
set lazyredraw
set showmatch
set backspace=indent,eol,start
set background=dark
set number
set encoding=utf-8
set ruler
